Repository ManageIQ/manageiq-documentation, pull requests merged in 2018-08, with the labels that each got.

#921 [WIP] Bz#1600413 scvmm
  doc-Installing_on_SCVMM/cfme/common
  doc-Installing_on_SCVMM/cfme/docinfo.xml
  doc-Installing_on_SCVMM/cfme/images
  doc-Installing_on_SCVMM/cfme/master.adoc
  doc-Installing_on_SCVMM/cfme/topics
  doc-Installing_on_SCVMM/images/4941.png
  doc-Installing_on_SCVMM/images/5780.png
  doc-Installing_on_SCVMM/images/7150.png
  doc-Installing_on_SCVMM/images/7151.png
  doc-Installing_on_SCVMM/images/7216.png
  doc-Installing_on_SCVMM/images/7217.png
  doc-Installing_on_SCVMM/images/7218.png
  doc-Installing_on_SCVMM/images/icon.svg
  doc-Installing_on_SCVMM/miq/common
  doc-Installing_on_SCVMM/miq/docinfo.xml
  doc-Installing_on_SCVMM/miq/images
  doc-Installing_on_SCVMM/miq/index.adoc
  doc-Installing_on_SCVMM/miq/topics
  doc-Installing_on_SCVMM/topics/installation.adoc
  doc-Installing_on_SCVMM/topics/topics
Labels: wip

#938 Corrected the version number for the SCVMM installation guide.
  doc-Installing_on_SCVMM/cfme/docinfo.xml
  doc-Installing_on_SCVMM/cfme/master.adoc
Labels: bug

#940 Working with Ansible Tower Workflows
  doc-Managing_Providers/topics/Automation_Management_Providers.adoc
Labels: enhancement

#944 Bz#1618982
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/assembly_Installation.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/con_Prerequisites.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Configuring_the_maximum_number_of_concurrent_migrations.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Creating_rhv_conversion_hosts.adoc
Labels: enhancement

#946 Add rename vmware vm procedure
  doc-Provisioning_Virtual_Machines_and_Hosts/topics/Provisioning_Requests.adoc
Labels: enhancement

#948 add delete datastore api
  doc-REST_API/topics/chap-Examples.adoc
  doc-REST_API/topics/delete_datastore.adoc
Labels: enhancement

#950 Bz#1621398
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/assembly_Installation.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/con_Prerequisites.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/con_Rhv_conversion_hosts.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Configuring_the_maximum_number_of_concurrent_migrations.adoc
Labels: enhancement

#949 add reset vm feature
  doc-Managing_Infrastructure_and_Inventory/topics/Controlling_Power_State_of_RHV_VMs.adoc
Labels: enhancement

#954 corrected ansible path
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Creating_and_configuring_rhv_conversion_hosts_for_ssh_transformation.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Creating_and_configuring_rhv_conversion_hosts_for_vddk_transformation.adoc
Labels: enhancement

#953 Note about icon appearance delay
  doc-Infrastructure_Migration_Solution_Guide/cfme/doc/modules/proc_Creating_an_Infrastructure_Mapping.adoc
  doc-Infrastructure_Migration_Solution_Guide/cfme/images/warning.png
Labels: enhancement
