Repository ManageIQ/manageiq-documentation, pull requests merged in 2019-12, with the labels that each got.

#1299 Enhanced OpenID-Connect authentication via the CLI
  auth/openid_connect.adoc
Labels: enhancement

#1276 [IVANCHUK] cherry-pick changes from master
  doc-Scripting_Actions/topics/Ansible_method.adoc
Labels: unmergeable

#1315 Remove Master SAML Processing URL
  auth/saml.adoc
Labels: bug, enhancement, fine/yes
