Repository ManageIQ/manageiq-documentation, pull requests merged in 2019-09, with the labels that each got.

#1216 Updated postgresql service name
  common/configuration-db.adoc
  doc-Appliance_Hardening_Guide/topics/DB_Password.adoc
  doc-Appliance_Hardening_Guide/topics/DB_SSL.adoc
  doc-General_Configuration/topics/Configuration.adoc
  doc-High_Availability_Guide/topics/Database_Failover.adoc
  doc-High_Availability_Guide/topics/Renaming_HA_appliances.adoc
Labels: wip

#1246 Add example for datetime filtering
  api/overview/filtering.adoc
Labels: enhancement

#1240 add note to copy catalog item proc
  doc-Provisioning_Virtual_Machines_and_Hosts/topics/Catalogs_and_Services.adoc
Labels: enhancement

#1258 [FINE] Update query.adoc
  api/overview/query.adoc
Labels: bug

#1257 Update query.adoc
  api/overview/query.adoc
Labels: bug
