Repository ManageIQ/manageiq-documentation, pull requests merged in 2020-07, with the labels that each got.

#1464 Fixed header in appendix of Deployment Planning Guide
  deployment_planning_guide/index.md
Labels: bug

#1465 Fix reference links [???] in md files and cleanup / fix formatting, etc.
  appliance_hardening_guide/_topics/db_ssl.md
  appliance_hardening_guide/_topics/ssl_certs.md
  assigning_custom_analysis_profile_to_vm/_topics/introduction.md
  assigning_custom_analysis_profile_to_vm/_topics/to_add_assign_profile_to_analysis_task_action.md
  assigning_custom_analysis_profile_to_vm/_topics/to_assign_policy_profile_to_vm.md
  assigning_custom_analysis_profile_to_vm/_topics/to_create_policy_profile_and_assign_vm_control_policy.md
  assigning_custom_analysis_profile_to_vm/_topics/to_create_vm_control_policy.md
  general_configuration/_topics/configuration.md
  general_configuration/_topics/settings_overview.md
  high_availability_guide/_topics/ha_roles.md
  high_availability_guide/_topics/haproxy.md
  high_availability_guide/_topics/overview.md
  installing_on_aws/_topics/additional_configuration.md
  installing_on_aws/_topics/installation.md
  installing_on_openshift_container_platform/_topics/configuring_external_auth_ocp.md
  installing_on_openshift_container_platform/_topics/post-installation.md
  managing_infrastructure_and_inventory/_topics/scaling_down_compute.md
  policies_and_profiles_guide/_topics/openscap_integration.md
  policies_and_profiles_guide/_topics/to_create_a_compliance_policy.md
Labels: bug

#1467 [IVANCHUK] Make ivanchuk act as the primary legacy docs repo
  _distro_map.yml
Labels: enhancement

#1468 Fix appliance_rpm_dir
  _data/product.yml
  auth/active_directory.md
  auth/ldap.md
  auth/openid_connect.md
  auth/saml.md
Labels: bug

#1470 Fix format of note on max_results_per_page and emphasize
  api/overview/pagination.md
Labels: bug, jansa/yes?

#1471 Fixing more ??? and non-working links
  _includes/openstack/adding-an-openstack-cloud-provider.md
  _includes/policies-creating-vm-control-policy.md
  _includes/provisioning-requests-openstack.md
  _includes/smartstate.md
  installing_on_red_hat_virtualization/_topics/installation.md
Labels: bug, jansa/yes?

#1466 Fix link to generate SSL certificates
  appliance_hardening_guide/_topics/db_ssl.md
Labels: bug
