Repository ManageIQ/manageiq-documentation, pull requests merged in 2020-10, with the labels that each got.

#1481 Change /self_service to /ui/service
  creating_a_service_for_vm_provisioning/_topics/provisioning_a_vm_using_ssui.md
  self_service_user_interface_guide/_topics/accessing_self_service_ui.md
Labels: bug, jansa/yes?

#1484 Remove files that are not linked to
  installing_on_aws/_topics/additional_configuration.md
  installing_on_red_hat_enterprise_linux_openstack_platform/_topics/additional_configuration.md
Labels: cleanup

#1488 Add section Planning Where to Put a New Virtual Machine PLUS fixing more links
  deployment_planning_guide/_topics/capacity.md
  managing_infrastructure_and_inventory/_topics/data_optimization_features.md
Labels: enhancement

#1489 Change RH URLs to relative links within MIQ docs
  managing_infrastructure_and_inventory/_topics/data_optimization_features.md
  managing_providers/_topics/enabling_red_hat_virtualization_cu.md
Labels: bug

#1490 Update ocp-metrics.md to fix Enabling Cluster Metrics link
  integration_with_openshift_container_platform/_topics/ocp-metrics.md
Labels: bug

#1494 Update adding_a_vmware_vcenter_provider.md for customer reported issue.
  managing_providers/_topics/adding_a_vmware_vcenter_provider.md
Labels: bug

#1495 Replacing redhat cloudforms URLs with relative links to ManageIQ docs
  _includes/create-playbook-service-catalog-item.md
  _includes/introduction.md
  _includes/openscap/openscap-overview.md
  _includes/openstack/adding-an-openstack-cloud-provider.md
  _includes/provider-ocp-add-container.md
  deployment_planning_guide/_topics/planning.md
  general_configuration/_topics/configuration.md
  high_availability_guide/_topics/ha_roles.md
  high_availability_guide/_topics/installation.md
Labels: bug

#1482 ManageIQ Appliance install on IBM Cloud
  images/buckets.png
  images/cloud_object_storage.png
  images/config_ACL.png
  images/data_volumes.png
  images/floating_ip_vpc.png
  images/import_custom_image.png
  images/new_virtual_server.png
  images/required_roles.png
  images/results_vpc_images.png
  images/security_inbound_outbound.png
  images/select_new_server.png
  images/select_qcow2_image.png
  images/service_auth_vpc.png
  images/setup_appliance.png
  images/ssh_keys.png
  images/upload_images_to_bucket.png
  installing_on_ibm_cloud/_topics/installation.md
  installing_on_ibm_cloud/index.md
Labels: enhancement

#1486 Add documentation for migrating from appliance(s) to pods
  _data/product.yml
  installing_on_kubernetes/_topics/migrate_from_appliance.md
  installing_on_kubernetes/_topics/prepare_kubernetes_namespace.md
  installing_on_kubernetes/index.md
Labels: documentation, enhancement

#1491 Add IBM Cloud Power Virtual Servers Provider Documentation
  _includes/provisioning-requests-ibm-cloud-powervs.md
  capabilities_matrix/_topics/cloud_providers.md
  images/ibm_cloud_powervs_guid.png
  managing_infrastructure_and_inventory/_topics/attaching_ibm_cloud_powervs_volumes.md
  managing_infrastructure_and_inventory/_topics/creating_ibm_cloud_powervs_volumes.md
  managing_infrastructure_and_inventory/_topics/deleting_ibm_cloud_powervs_volumes.md
  managing_infrastructure_and_inventory/_topics/detaching_ibm_cloud_powervs_volumes.md
  managing_infrastructure_and_inventory/_topics/volumes.md
  managing_providers/_topics/adding_ibm_cloud_powervs_providers.md
  managing_providers/_topics/cloud_providers.md
  managing_providers/_topics/overview_ibm_cloud_powervs.md
  provisioning_virtual_machines_and_hosts/_topics/provisioning_requests.md
Labels: enhancement

#1498 Updating Red Hat CloudForms URLs to relative links in ManageIQ
  high_availability_guide/_topics/updating_ha.md
  installing_on_microsoft_azure/_topics/installation.md
  installing_on_openshift_container_platform/_topics/appe-saml-authentication-example.md
  managing_authentication/_topics/authentication_overview.md
  managing_authentication/_topics/external_ad.md
  managing_authentication/_topics/ldap.md
  managing_authentication/_topics/saml.md
  managing_infrastructure_and_inventory/_topics/container_entities.md
  managing_infrastructure_and_inventory/_topics/tenants.md
  managing_providers/_topics/containers_providers.md
  managing_providers/_topics/editing_a_containers_provider.md
  managing_providers/_topics/hide_environment_vars.md
  managing_providers/index.md
  monitoring_alerts_and_reporting/_topics/to_schedule_a_report.md
  provisioning_virtual_machines_and_hosts/_topics/fulfilling_requests.md
  provisioning_virtual_machines_and_hosts/_topics/provisioning_requests.md
  quickstart_openstack_provider_guide/_topics/catalogs-services.md
  quickstart_openstack_provider_guide/index.md
  rest_api/_topics/scan_containers.md
  scripting_actions/_topics/ansible_method.md
Labels: bug

#1499 fix rhv installation doc format
  installing_on_red_hat_virtualization/_topics/installation.md
Labels: bug

#1501 [JANSA] Transfer site menu from ManageIQ/manageiq.org
  _data/site_menu.yml
Labels: refactoring

#1502 [IVANCHUK] Transfer site menu from ManageIQ/manageiq.org
  site_menu.yml
Labels: refactoring

#1503 [HAMMER] Transfer site menu from ManageIQ/manageiq.org
  site_menu.yml
Labels: refactoring

#1504 [GAPRINDASHVILI] Transfer site menu from ManageIQ/manageiq.org
  site_menu.yml
Labels: refactoring

#1505 [FINE] Transfer site menu from ManageIQ/manageiq.org
  site_menu.yml
Labels: refactoring

#1506 [EUWE] Transfer site menu from ManageIQ/manageiq.org
  site_menu.yml
Labels: refactoring

#1500 Transfer site menu from ManageIQ/manageiq.org
  _data/site_menu.yml
Labels: refactoring
