Repository ManageIQ/manageiq-documentation, pull requests merged in 2020-04, with the labels that each got.

#1396 Cleanup doc errors and warnings
  _topic_map.yml
  api/overview/auth.adoc
  api/overview/usage_examples.adoc
  auth/ldap.adoc
  doc-Appliance_Hardening_Guide/miq/images
  doc-General_Configuration/miq/index.adoc
  doc-High_Availability_Guide/miq/index.adoc
  doc-Installing_on_AWS/miq/index.adoc
  doc-Installing_on_AWS/topics/installation.adoc
  doc-Installing_on_Google_Compute_Engine/topics/installation.adoc
  doc-Installing_on_Microsoft_Azure/topics/installation.adoc
  doc-Installing_on_Red_Hat_Enterprise_Linux_OpenStack_Platform/topics/installation.adoc
  doc-Installing_on_Red_Hat_Virtualization/topics/installation.adoc
  doc-Installing_on_SCVMM/miq/index.adoc
  doc-Installing_on_SCVMM/topics/installation.adoc
  doc-Installing_on_VMware_vSphere/miq/index.adoc
  doc-Installing_on_VMware_vSphere/topics/additional_configuration.adoc
  doc-Installing_on_VMware_vSphere/topics/common
  doc-Installing_on_VMware_vSphere/topics/installation.adoc
  doc-Managing_Infrastructure_and_Inventory/topics/Virtual_Machines.adoc
  doc-Managing_Providers/topics/Adding_Ansible_Galaxy_Roles.adoc
  doc-Managing_Providers/topics/Ansible_Service_Linking.adoc
  doc-Managing_Providers/topics/Nonadmin_VMware_vCenter_Auth.adoc
  doc-Monitoring_Alerts_and_Reporting/topics/appe-Reportable_Fields.adoc
  doc-Provisioning_Virtual_Machines_and_Hosts/topics/Catalogs_and_Services.adoc
  doc-REST_API/topics/delete_datastore.adoc
  doc-Self_Service_User_Interface_Guide/miq/index.adoc
Labels: bug, enhancement

#1397 Correct wording for AWS
  _topic_map.yml
Labels: bug

#1402 Fixed download link
  doc-Installing_on_AWS/topics/installation.adoc
  doc-Installing_on_Google_Compute_Engine/topics/installation.adoc
  doc-Installing_on_Microsoft_Azure/topics/installation.adoc
  doc-Installing_on_Red_Hat_Enterprise_Linux_OpenStack_Platform/topics/installation.adoc
  doc-Installing_on_Red_Hat_Virtualization/topics/installation.adoc
  doc-Installing_on_SCVMM/topics/installation.adoc
  doc-Installing_on_VMware_vSphere/topics/installation.adoc
  doc-QuickStart_OpenStack_Provider_Guide/miq/index.adoc
Labels: bug

#1401 in ManageIQ and common docs, changed CloudForms to variable
  art-Service_Provisioning_Using_an_Orchestration_Template/miq/index.adoc
  doc-Appliance_Hardening_Guide/topics/Firewall.adoc
  doc-General_Configuration/topics/Configuration.adoc
  doc-High_Availability_Guide/topics/HAProxy.adoc
  doc-Installing_on_VMware_vSphere/miq/docinfo.xml
  doc-Managing_Authentication/topics/LDAP.adoc
  doc-Managing_Providers/topics/Automation_Management_Providers.adoc
  doc-Provisioning_Virtual_Machines_and_Hosts/topics/Catalogs_and_Services.adoc
Labels: bug

#1403 Azure appliance image no longer need to be resized manually
  doc-Installing_on_Microsoft_Azure/topics/converting-aligning-cfme-appliance-image.adoc
  doc-Installing_on_Microsoft_Azure/topics/installation.adoc
Labels: bug

#1320 request token cli parameter error
  api/overview/auth.adoc
Labels: bug

#985 Add section on Block Storage targeted refresh
  doc-Managing_Providers/topics/Storage_Managers.adoc
Labels: enhancement

#1410 Preferring the "request_retire" action over the older "retire".
  api/examples/custom_action_service.adoc
Labels: bug

#1409 Adding the queue_chargeback_report action for the services api doc page.
  api/reference/services.adoc
Labels: enhancement

#1408 Fixed section about Network Manager for Active Directory.
  auth/active_directory.adoc
Labels: bug

#962 Add detail on ha_admin.yml config file to HA Guide
  doc-High_Availability_Guide/topics/Database_Failover.adoc
Labels: enhancement

#1390 API - Adding an example of a compliance policy usage flow.
  _topic_map.yml
  api/examples/compliance_policy_flow.adoc
Labels: enhancement

#1407 update final retirement call
  api/reference/vms.adoc
Labels: bug

#1412 Add example dialog id to custom button create
  api/reference/custom_buttons.adoc
Labels: ivanchuck/backport

#1411 Fix example for POST /api/rates
  api/reference/chargebacks_rates.adoc
Labels: bug

#1431 Enhanced documentation for the group filtering
  api/appendices/resource_attributes.adoc
Labels: enhancement

#1426 Update overview image - replacing virtual desktops with containers
  doc-Deployment_Planning_Guide/images/1845.png
Labels: bug

#1404 Remove pause/resume documentation for Container Providers
  doc-Managing_Providers/topics/Containers_Providers.adoc
Labels: bug

#1437 Update tagging.adoc
  api/reference/tagging.adoc
Labels: enhancement

#1438 Updated the Collections page to reflect the latest API collections
  api/reference/collections.adoc
Labels: enhancement
