Repository ManageIQ/manageiq-documentation, pull requests merged in 2021-06, with the labels that each got.

#1573 Add steps for creating the OCP service account
  managing_providers/_topics/containers_providers.md
Labels: documentation

#1581 Update adding_a_red_hat_virtualization_provider.md
  managing_providers/_topics/adding_a_red_hat_virtualization_provider.md
Labels: bug, documentation

#1572 Shrink the header titles on the capabilities matrix
  capabilities_matrix/_topics/browsers.md
  capabilities_matrix/_topics/cloud_providers.md
  capabilities_matrix/_topics/container_providers.md
  capabilities_matrix/_topics/infrastructure_providers.md
  capabilities_matrix/_topics/network_providers.md
  capabilities_matrix/_topics/providers.md
  capabilities_matrix/_topics/runtime_platforms.md
  capabilities_matrix/_topics/smartstate_analysis.md
Labels: cleanup

#1582 Clarify Chargeback Capabilities for Cloud Providers
  capabilities_matrix/_topics/cloud_providers.md
Labels: refactoring

#1583 Clarify Chargeback Capabilities for Infra Providers
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: refactoring
