Repository ManageIQ/manageiq-documentation, pull requests merged in 2021-08, with the labels that each got.

#1588 Add Google Kubernetes Engine to Capabilities Matrix
  capabilities_matrix/_topics/container_providers.md
Labels: enhancement

#1589 Add documentation for running a RPM upgrade
  _data/site_menu.yml
  upgrading_appliances/index.md
Labels: enhancement

#1591 Fix REST API link
  _data/site_menu.yml
Labels: bug, morphy/no

#1592 Add branch release tasks
  Rakefile
Labels: enhancement, tools, morphy/yes
