Repository ManageIQ/manageiq-documentation, pull requests merged in 2021-01, with the labels that each got.

#1528 Delete old OCP 3.7 installation documentation
  installing_on_openshift_container_platform/_topics/appe-saml-authentication-example.md
  installing_on_openshift_container_platform/_topics/configuring_external_auth_ocp.md
  installing_on_openshift_container_platform/_topics/installation.md
  installing_on_openshift_container_platform/_topics/post-installation.md
  installing_on_openshift_container_platform/_topics/troubleshooting.md
  installing_on_openshift_container_platform/index.md
Labels: technical debt

#1530 Fix task typo
  api/reference/tasks.md
Labels: bug

#1531 api/overview/auth: mention no challenge for HTTP Basic
  api/overview/auth.md
Labels: enhancement
