Repository ManageIQ/manageiq-documentation, pull requests merged in 2021-03, with the labels that each got.

#1534 Add Oracle Cloud to providers capabilities matrix
  capabilities_matrix/_topics/cloud_providers.md
Labels: enhancement

#1536 Add Amazon EKS to capabilities matrix
  capabilities_matrix/_topics/container_providers.md
Labels: enhancement

#1537 Minor fixes
  capabilities_matrix/_topics/container_providers.md
  capabilities_matrix/_topics/runtime_platforms.md
Labels: cleanup

#1538 Condensed Console in Cloud Providers
  capabilities_matrix/_topics/cloud_providers.md
Labels: cleanup

#1540 Convert capabilities from plaintext to emoji
  capabilities_matrix/_topics/automation_providers.md
  capabilities_matrix/_topics/cloud_providers.md
  capabilities_matrix/_topics/container_providers.md
  capabilities_matrix/_topics/infrastructure_providers.md
  capabilities_matrix/_topics/smartstate_analysis.md
Labels: enhancement

#1539 Fix product name in Runtime Platforms
  capabilities_matrix/_topics/runtime_platforms.md
Labels: bug

#1541 Reorganized Infrastructure Provider Capabilities
  capabilities_matrix/_topics/cloud_providers.md
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: refactoring

#1542 Minor Fixes to Capabilities
  capabilities_matrix/_topics/cloud_providers.md
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: cleanup

#1545 Add IBM Cloud VPC to the capabilities matrix
  capabilities_matrix/_topics/cloud_providers.md
Labels: enhancement

#1547 Add entry for network providers in capabilities matrix
  capabilities_matrix/_topics/network_providers.md
  capabilities_matrix/index.md
Labels: enhancement

#1516 [API] Add docs for scheduling a report
  api/reference/reports.md
Labels: enhancement

#1549 Update Oracle Cloud Capabilities
  capabilities_matrix/_topics/cloud_providers.md
Labels: documentation

#1548 Update database instructions
  _includes/configuration-advanced.md
  _includes/configuration-db.md
  _includes/configuration.md
  general_configuration/_topics/configuration.md
  high_availability_guide/_topics/installation.md
Labels: enhancement
