Repository ManageIQ/manageiq-documentation, pull requests merged in 2021-04, with the labels that each got.

#1553 Remove "Discovery - Providers" capability from container_providers
  capabilities_matrix/_topics/container_providers.md
Labels: documentation

#1555 Fix broken link to REST API docs
  _data/site_menu.yml
Labels: bug

#1556 Fix provisioning request broken link to REST API docs
  provisioning_virtual_machines_and_hosts/_topics/provisioning_requests.md
Labels: bug

#1561 'Add to access token' flag set to ON to make it works with SSUI
  auth/openid_connect.md
Labels: bug

#1564 Correct inaccurate IBM PowerVC via the OpenStack API capabilities
  capabilities_matrix/_topics/cloud_providers.md
Labels: bug

#1565 Update UI navigation continued
  managing_infrastructure_and_inventory/_topics/adding_a_cloud_network.md
  managing_infrastructure_and_inventory/_topics/container_entities.md
Labels: cleanup

#1567 Update the OCP Add Container Docs for Alerts/Metrics
  _includes/provider-ocp-add-container.md
Labels: bug, documentation

#1566 UI Navigation updates continued
  general_configuration/_topics/my_settings.md
  general_configuration/_topics/settings_overview.md
  general_configuration/_topics/smart_proxies.md
  general_configuration/_topics/tasks.md
Labels: cleanup
