Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-01, with the labels that each got.

#1631 Add IBM Power HMC to provider capabilities matrix
  capabilities_matrix/_topics/infrastructure_providers.md
  capabilities_matrix/_topics/providers.md
Labels: enhancement

#1632 Selecting a VMware Remote Console Type not required
  managing_infrastructure_and_inventory/_topics/vnc_and_spice_consoles.md
Labels: lasker/yes?, morphy/yes?

#1635 IKS metrics capture configuration documentation
  managing_providers/containers_providers/ibm_cloud_kubernetes_service_providers.md
Labels: enhancement

#1638 Fix left-side nav container providers section
  _data/site_menu.yml
Labels: bug

#1633 Add IBM Power HMC provider doc
  _data/site_menu.yml
  managing_providers/_topics/infrastructure_providers.md
  managing_providers/infrastructure_providers/_topics/adding_an_ibm_power_hmc_provider.md
  managing_providers/infrastructure_providers/ibm_power_hmc_providers.md
Labels: documentation
