Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-02, with the labels that each got.

#1617 Use OS certificate bundle
  appliance_hardening_guide/_topics/db_ssl.md
Labels: enhancement

#1643 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
Labels: developer, test

#1644 Fix issue where no modifications fails the release
  Rakefile
Labels: bug

#1642 added minimal PowerVC version requirement
  managing_providers/cloud_providers/_topics/adding_ibm_power_vc_providers.md
Labels: enhancement

#1646 Update topic markown headings
  deleting_a_router.md
  deleting_a_security_group.md
Labels: bug, najdorf/yes?

#1647 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
