Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-10, with the labels that each got.

#1692 Appliances no longer initialize on first boot
  high_availability_guide/_topics/installation.md
Labels: bug

#1694 Updated topics
  managing_providers/_topics/ansible_credentials.md
  managing_providers/_topics/automation_management_providers.md
  managing_providers/_topics/tagging_ansible_elements.md
Labels: bug, oparin/yes?

#1696 Upgrade workflows to actions/checkout@v3
  .github/workflows/ci.yaml
Labels: enhancement, test

#1698 Update image_import.md
  managing_providers/_topics/image_import.md
Labels: bug, oparin/yes?

#1697 Update fulfilling_requests.md
  provisioning_virtual_machines_and_hosts/_topics/fulfilling_requests.md
Labels: bug, oparin/yes?

#1695 Update messaging documentation
  _includes/configuration-advanced.md
  _includes/configuration.md
Labels: enhancement

#1700 Correct the path to the ha_admin.yml
  high_availability_guide/_topics/database_failover.md
Labels: bug
