Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-12, with the labels that each got.

#1704 Update tokens for ci workflow
  .github/workflows/ci.yaml
Labels: developer

#1705 Add RHV/Ovirt OVN Operations Capabilities
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: documentation

#1706 Add a document on installing the VMware VDDK on containers
  installing_on_kubernetes/_topics/installing_vddk.md
  installing_on_kubernetes/index.md
Labels: enhancement

#1707 Add workflow_dispatch to enable manual builds
  .github/workflows/ci.yaml
Labels: developer
