Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-05, with the labels that each got.

#1669 Update installation.md
  installing_on_aws/_topics/installation.md
Labels: najdorf/yes?

#1663 RW-Update assign_service_templates.md
  api/examples/assign_service_templates.md
Labels: najdorf/yes?

#1671 Upgrade build to Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies

#1672 Add Oracle Cloud docs
  managing_providers/_topics/cloud_providers.md
  managing_providers/cloud_providers/_topics/adding_oracle_cloud_providers.md
  managing_providers/cloud_providers/oracle_cloud_providers.md
Labels: documentation

#1674 [MORPHY] Update installation.md
  installing_on_vmware_vsphere/_topics/installation.md
Labels: enhancement

#1676 Add cloud database CRUD operations to capabilities matrix
  capabilities_matrix/_topics/cloud_providers.md
Labels: enhancement
