Repository ManageIQ/manageiq-documentation, pull requests merged in 2022-03, with the labels that each got.

#1648 Changed the configuration.md
  _includes/configuration-db.md
  _includes/configuration.md
Labels: enhancement

#1652 Replace CloudForms with product title_short in Scription Actions
  scripting_actions/index.md
Labels: bug

#1650 Remove hard-coded "CloudForms" from service_provisioning
  service_provisioning_using_an_orchestration_template/index.md
Labels: bug, najdorf/yes?

#1651 Replace CloudForms with product title_short in rhv installation
  installing_on_red_hat_virtualization/_topics/installation.md
Labels: bug

#1654 Drop usage of site.data.product.title_abbr
  _data/product.yml
  installing_on_microsoft_azure/_topics/installation.md
Labels: technical debt, najdorf/yes?

#1641 Updated configuration.md
  _includes/configuration.md
  deleting_a_router.md
  deleting_a_security_group.md
  installing_on_vmware_vsphere/_topics/installation.md
Labels: unmergeable, cleanup
