Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-07, with the labels that each got.

#1735 Remove scheduling of database backups from documentation
  general_configuration/_topics/configuration.md
Labels: technical debt

#1734 Fix missing method v2_key
  installing_on_kubernetes/_topics/migrate_from_appliance.md
Labels: bug, najdorf/yes?, oparin/yes?, petrosian/yes?

#1737 enabling ibm_powervc events
  managing_providers/cloud_providers/_topics/enabling_ibm_power_vc_events.md
  managing_providers/cloud_providers/ibm_power_vc_providers.md
Labels: enhancement, petrosian/no
