Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-11, with the labels that each got.

#1759 Update embedded_workflows.md
  managing_providers/_topics/embedded_workflows.md
Labels: enhancement, documentation

#1736 dropping references to vm lifecycle events
  api/appendices/soap_to_rest.md
  api/examples/add_lifecycle_event_vm.md
  api/examples/compliance_policy_flow.md
  api/reference/custom_actions.md
  api/reference/vms.md
Labels: stale, technical debt

#1758 Fix appliance backup and restore numbered lists
  appliances/backup_and_restore.md
Labels: bug, quinteros/yes?

#1760 Add procedure to specify docker pull secret for embedded workflow
  managing_providers/_topics/embedded_workflows.md
Labels: bug, quinteros/yes

#1764 Add CIC to provider section of capabilities matrix
  capabilities_matrix/_topics/providers.md
Labels: bug

#1765 Fix capabilities matrix
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: bug, petrosian/yes?, quinteros/yes

#1766 Better indenting and bullets
  capabilities_matrix/_topics/cloud_providers.md
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: enhancement

#1762 Embedded Workflows on OCP docker custom pull secret
  managing_providers/_topics/embedded_workflows.md
Labels: enhancement
