Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-02, with the labels that each got.

#1720 Advise one Kafka broker per region
  _includes/configuration.md
Labels: enhancement

#1719 Ms 35488: : Updated Editing the Default State Instance and Customizing Provisioning States sections
  provisioning_virtual_machines_and_hosts/_topics/fulfilling_requests.md
Labels: bug, oparin/yes?

#1721 Update installation.md
  installing_on_aws/_topics/installation.md
Labels: bug, oparin/yes?

#1722 Change the docs for journalctl to bullets for better rendering
  troubleshooting/_topics/appliance_logging.md
Labels: cleanup, oparin/yes

#1715 Update steps for getting the admin token for OCP
  _includes/provider-ocp-mgt-token.md
  _includes/provider-ose-mgt-token-3_1.md
  _includes/provider-ose-mgt-token-3_2.md
  capabilities_matrix/_topics/container_providers.md
  integration_with_openshift_container_platform/_topics/ocp-retrieve-tokens.md
  managing_providers/containers_providers/red_hat_openshift_providers.md
Labels: technical debt
