Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-10, with the labels that each got.

#1748 Remove SCVMM from Capabilities Matrix
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: petrosian/yes?, quinteros/yes?

#1749 Add documentation for scheduling database backups using crontab
  appliances/backup_and_restore.md
Labels: enhancement, petrosian/yes?, quinteros/yes?

#1750 Update automation_providers.md
  capabilities_matrix/_topics/automation_providers.md
Labels: petrosian/yes?, quinteros/yes?

#1746 Enable events syndication
  general_configuration/_topics/configuration.md
Labels: enhancement

#1751 Update event syndication enablement content
  general_configuration/_topics/configuration.md
Labels: enhancement, documentation, quinteros/yes?

#1755 Consolidate VMWare VDDK docs to a central location
  _includes/installing-vmware-vddk-containers.md
  _includes/installing-vmware-vddk.md
  installing_on_kubernetes/_topics/installing_vddk.md
  installing_on_kubernetes/index.md
  installing_on_vmware_vsphere/_topics/additional_configuration.md
  managing_infrastructure_and_inventory/_topics/installing_vmware_vddk.md
  managing_infrastructure_and_inventory/_topics/virtual_machines.md
Labels: enhancement, quinteros/yes

#1752 Add Embedded Workflows content
  images/embedworkflow_addnewrepository.png
  images/embedworkflow_addnewrepository_details.png
  images/embedworkflow_entrypointsembedded.png
  images/embedworkflow_graphView.png
  images/embedworkflow_orderservicecatalog.png
  images/embedworkflow_runstatus.png
  images/embedworkflow_servicedialogdynamic.png
  images/embedworkflow_textview.png
  images/embedworkflow_ui.png
  images/embedworkflow_workflownumbers.png
  managing_providers/_topics/automation_management_providers.md
  managing_providers/_topics/embedded_workflows.md
Labels: documentation, quinteros/yes?
