Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-04, with the labels that each got.

#1725 Remove hawkular metrics documentation
  _includes/provider-ocp-add-container.md
  api/reference/providers.md
  api/reference/settings.md
  integration_with_openshift_container_platform/_topics/ocp-metrics.md
  integration_with_openshift_container_platform/index.md
  managing_providers/_topics/editing_a_containers_provider.md
Labels: technical debt, oparin/yes?, petrosian/yes?

#1727 Add documentation on the usage of the collect_logs utilities
  troubleshooting/_topics/appliance_logging.md
Labels: documentation

#1726 Added log table request information
  provisioning_virtual_machines_and_hosts/_topics/fulfilling_requests.md
Labels: bug, petrosian/yes?

#1729 Add docs on enabling collection of capacity and utilization data for PowerVC
  managing_providers/cloud_providers/_topics/enabling_cu_data_from_ibm_power_vc_providers.md
  managing_providers/cloud_providers/ibm_power_vc_providers.md
Labels: enhancement, petrosian/yes
