Repository ManageIQ/manageiq-documentation, pull requests merged in 2023-09, with the labels that each got.

#1741 Add root key to internal certificate secret example
  installing_on_kubernetes/_topics/pods_ssl.md
Labels: enhancement

#1744 Remove prior now that #1740 has been backported down to najdorf
  _data/site_menu.yml
Labels: cleanup

#1747 Fix remote-console cert keys
  installing_on_kubernetes/_topics/pods_ssl.md
Labels: bug
