Repository ManageIQ/manageiq-documentation, pull requests merged in 2024-07, with the labels that each got.

#1796 Minor updates to product.yml and variable usage
  _data/product.yml
  managing_providers/_topics/automation_management_providers.md
Labels: radjabov/yes?

#1795 QA Update installation.md
  installing_on_google_compute_engine/_topics/installation.md
Labels: enhancement, radjabov/yes?

#1797 QA Updated KubeVirt references
  _includes/provider-ocp-add-container.md
  capabilities_matrix/_topics/infrastructure_providers.md
  capabilities_matrix/_topics/providers.md
  managing_providers/_topics/infrastructure_providers.md
  managing_providers/infrastructure_providers/kubevirt_providers.md
Labels: quinteros/yes?, radjabov/yes?

#1798 Mention optional messaging disk in requirements
  _includes/introduction.md
Labels: enhancement, radjabov/yes?

#1799 Minor changes
  managing_providers/_topics/automation_management_providers.md
  managing_providers/_topics/opentofu_credentials.md
Labels: radjabov/yes?
