Repository ManageIQ/manageiq-documentation, pull requests merged in 2024-10, with the labels that each got.

#1816 QA Removed SCVMM provider
  _data/site_menu.yml
  managing_providers/_topics/infrastructure_providers.md
  managing_providers/infrastructure_providers/_topics/adding_a_microsoft_system_center_virtual_machine_manager_provider.md
  managing_providers/infrastructure_providers/_topics/authenticating_to_microsoft_scvmm.md
  managing_providers/infrastructure_providers/microsoft_scvmm_providers.md
Labels: technical debt, petrosian/yes?, quinteros/yes?, radjabov/yes?

#1815 Differentiate between Kubevirt and OpenShift Virtualization
  _includes/provider-ocp-add-container.md
  capabilities_matrix/_topics/providers.md
Labels: enhancement, radjabov/yes?

#1817 Floe features not yet supported
  managing_providers/_topics/embedded_workflows.md
Labels: enhancement
