Repository ManageIQ/manageiq-documentation, pull requests merged in 2024-12, with the labels that each got.

#1821 QA Minor change to OpenTofu command description.
  _data/product.yml
  managing_providers/_topics/automation_management_providers.md
Labels: radjabov/yes?

#1823 Add instructions on enabling VMware Request Debugging
  troubleshooting/_topics/providers.md
  troubleshooting/index.md
Labels: documentation

#1826 Fix issue with invalid yaml
  _data/product.yml
  managing_providers/_topics/automation_management_providers.md
Labels: bug, radjabov/yes?

#1825 Kubevirt/OSV Capabilities Update
  capabilities_matrix/_topics/infrastructure_providers.md
Labels: enhancement

#1811 Add documentation on enabling Microsoft.Insights for Azure Events / Metrics
  images/azure-microsoft-insights.png
  managing_providers/cloud_providers/_topics/adding_azure_providers.md
Labels: enhancement

#1828 Upgrade Ruby to 3.3 and jekyll to 4.3
  .github/workflows/ci.yaml
  Gemfile
Labels: dependencies
