Repository ManageIQ/manageiq-documentation, pull requests merged in 2024-01, with the labels that each got.

#1773 Add documentation on setting credentials in workflows
  managing_providers/_topics/embedded_workflows.md
Labels: documentation

#1769 Strimzi installation on Kubernetes
  installing_on_kubernetes/_topics/prepare_kubernetes_namespace.md
Labels: enhancement, quinteros/yes?

#1777 Messaging configuration hostname guidelines
  _includes/configuration.md
  installing_on_aws/index.md
Labels: enhancement, quinteros/yes?

#1778 Messaging hostname guideline updates
  _includes/configuration.md
  installing_on_aws/index.md
Labels: enhancement, quinteros/yes?

#1780 Specify internal FQDN for messaging hostname
  _includes/configuration.md
Labels: enhancement, quinteros/yes

#1781 Revert #1780 and specify adding hostname to /etc/hosts
  _includes/configuration.md
Labels: enhancement, quinteros/yes
