Repository ManageIQ/manageiq-documentation, pull requests merged in 2024-08, with the labels that each got.

#1804 Update OIDC group mapper config
  auth/openid_connect.md
Labels: enhancement

#1805 Minor updates to Installing on Google Compute Engine topic
  _includes/configuration-db-external.md
  _includes/configuration-db-internal.md
  _includes/configuration.md
  _includes/initial-login-changepw.md
  _includes/initial-login.md
Labels: enhancement, radjabov/yes?

#1808 Update embedded_workflows.md
  managing_providers/_topics/embedded_workflows.md
Labels: radjabov/yes?

#1810 Update embedded_workflows.md
  managing_providers/_topics/embedded_workflows.md
Labels: documentation, radjabov/yes?
