Repository ManageIQ/manageiq-documentation, pull requests merged in 2025-06, with the labels that each got.

#1847 Add Terraform Enterprise Documentation
  managing_providers/_topics/automation_management_providers.md
  managing_providers/automation_providers/ansible_tower_providers.md
  managing_providers/automation_providers/embedded_ansible_providers.md
Labels: documentation, spassky/yes

#1850 Delete accidentally added automation_providers directory
  managing_providers/automation_providers/ansible_tower_providers.md
  managing_providers/automation_providers/embedded_ansible_providers.md
Labels: bug

#1851 Add a guide for migrating from pods to appliances
  installing_on_kubernetes/_topics/migrate_to_appliance.md
  installing_on_kubernetes/index.md
Labels: enhancement
