Repository ManageIQ/manageiq-documentation, pull requests merged in 2025-01, with the labels that each got.

#1829 QA Added new topic for IBM CIC provider
  _data/site_menu.yml
  managing_providers/cloud_providers/_topics/adding_ibm_cic_providers.md
  managing_providers/cloud_providers/ibm_cic_providers.md
Labels: enhancement, radjabov/yes?

#1830 [RADJABOV] Fix link references
  _data/site_menu.yml
Labels: bug

#1831 QA Improved content for add azure microsoft insights provider instructions
  managing_providers/cloud_providers/_topics/adding_azure_providers.md
Labels: radjabov/yes?

#1834 QA Updated Terraform template variables section
  managing_providers/_topics/automation_management_providers.md
Labels: enhancement, radjabov/yes?

#1835 QA Added link for CIC within Cloud Providers section
  managing_providers/_topics/cloud_providers.md
Labels: radjabov/yes?

#1833 IBM Cloud VPC Metrics Capabilities Update
  capabilities_matrix/_topics/cloud_providers.md
Labels: enhancement

#1837 Fix image URLs + minor edits for text to appear correctly on line
  managing_providers/cloud_providers/_topics/adding_azure_providers.md
  managing_providers/cloud_providers/_topics/adding_google_compute_engine_providers.md
  managing_providers/cloud_providers/_topics/enabling_gce_events.md
  managing_providers/storage_providers/ibm_cloud_object_storage_managers.md
  provisioning_virtual_machines_and_hosts/_topics/cfme_lifecycle.md
  provisioning_virtual_machines_and_hosts/_topics/provisioning_requests.md
Labels: radjabov/yes?
