Repository ManageIQ/manageiq-documentation, pull requests merged in 2025-04, with the labels that each got.

#1841 Fix broken link to azure docs for adding an App
  managing_providers/cloud_providers/_topics/adding_azure_providers.md
Labels: bug, radjabov/yes?, spassky/yes?

#1843 Fix link to Configuring WebMKS Support
  managing_infrastructure_and_inventory/_topics/vnc_and_spice_consoles.md
Labels: bug

#1845 Fix broken links on API services page
  api/reference/services.md
Labels: bug, spassky/yes?
